# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

home = ["HTML", "JSON", "Atom", "RSS", "SearchIndex"]
page = ["HTML"]
section = ["HTML", "Atom", "RSS", "SearchIndex"]
taxonomy = ["HTML", "Atom", "RSS", "SearchIndex"]
term = ["HTML", "Atom", "RSS", "SearchIndex"]
