# See: https://gohugo.io/getting-started/configuration/#merge-configuration-from-themes
_merge = "deep"

jquerycdn = true

favicon_mstilecolor = "#ffffff"

### BGN: Structured Data ###
  siteStartYear = 2003
  description = "Science and Technology Playground"
  keywords = ["techmagus", "テク魔法使い", "ハイテク マギ", "테크마법사", "테크 마구스", "YourOnlyOne", "YourOnly.One", "Yahuhanan Yukiya Sese Cuneta", "Yuki", "YoHan", "Yo-Han",  "יהוחנן", "ᜌᜓᜃᜒ", "사요한", "謝雪矢（ゆきや）", "스노", "Seu-No", "SeuNo", "Snow", "Yohanan", "ᜌᜓᜑᜈᜈ᜔", "ᜌᜓᜑᜈᜈ᜕", "ᜌᜑᜓᜑᜈᜈ᜔", "ᜌᜑᜓᜑᜈᜈ᜕"] # Can be overriden per page
  images = ["https://rsc.youronly.one/img/y/techmagus-smartphone-1920x1280.webp", "https://rsc.youronly.one/img/y/techmagus-Architetto-Esperiment-chimico.webp"]
### END: Structured Data ###

### BGN: Theme settings
  #logoText = "techmagus"                                                     # We are not using this
  logoType = "short" # long, short
  #custom_css = []
  #custom_js = []
  useFaviconGenerator = false # https://www.favicon-generator.org/
  meta_image = ""
  themecolor = ""

  themeOptions = ["kimbie", "solarized", "hacker", "light", "dark"]
  notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
  notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
  notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
  notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

  viewportSize = "wide" # widest, wider, wide, normal, narrow
  enableUiAnimation = true
  hideSingleContentsWhenJSDisabled = false
  enablePinnedPosts = true
  minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

  # appbar
  enableAppbarSearchIcon = true # YELOSAN: not working as of 2023-03-30
  enableAppbarLangIcon = true

  # header
  homeHeaderType = "text" # text, img, slide, typewriter
  hideHomeHeaderWhenMobile = false

  # menu
  showMobileMenuTerms = ["series", "categories", "tags"]

  # search
  enableSearch = true # YELOSAN: not working as of 2023-03-30
  enableSearchHighlight = true
  searchResultPosition = "side" # side, main
  searchContent = true # include content to search index
  searchDistance = 100 # fuse option
  searchThreshold = 0.5 # 0.0: exact match, 1.0: any match

  # body
  enableBreadcrumb = false
  enableGoToTop = true
  enableWhoami = false
  summaryShape = "classic" # card, classic, compact
  archiveGroupBydate = "2006-01" # "2006-01": group by month, "2006: group by year
  archivePaginate = 10
  paginateWindow = 1
  talksPaginate = 5
  talksGroupBydate = "2006-01"
  pubPaginate = 20
  writtenTimeIcon = "📅"
  modifiedTimeIcon = "📝"
  readingTimeIcon = "☕"
  #authorIcon = "✍️"                                                            # We are not using this.
  pagePvIcon = "👀"
  pinIcon = "📌"
  tagIcon = "🏷️"
  publicationIcon = "📚"
  typeIcon = "🎯"

  # We are not using this
  # whoami
  #myname = ""
  #email = ""
  #whoami = ""
  #bioImageUrl = ""
  #useGravatar = false
  #location = ""
  #organization = ""
  #link = ""

  # sidebar
  enableBio = false
  enableBioImage = true
  enableSidebar = true
  enableSidebarTags = true
  enableSidebarSeries = true
  enableSidebarCategories = true
  enableSidebarChannels = false
  enableHomeSidebarTitles = true
  enableListSidebarTitles = true
  enableToc = true
  hideToc = false
  tocFolding = true
  tocPosition = "inner" # inner, outer
  enableTocSwitch = false
  itemsPerCategory = 5
  sidebarPosition = "right"
  tocLevels = ["h2", "h3", "h4"]
  enableSidebarPostsByOrder = false

  # footer
  showPoweredBy = true
  showFeedLinks = true
  showSocialLinks = true
  enableLangChange = true
  enableThemeChange = true

  # service
  #googleTagManager = ""
  #baiduAnalytics = ""
  enableBusuanzi = false
  busuanziSiteUV = true
  busuanziSitePV = true
  busuanziPagePV = true

  # rss
  updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
  updateFrequency = ""
  fullContents = true

  # comment
  enableComment = true
  #disqus_shortname = ""                                          # We are using the default disqus param
  commento = false

  [telegram]
    enable = false
    #siteId = ""
    #dataLimit = 5

  #[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    #owner = ""              # Your GitHub ID
    #repo = ""               # The repo to store comments
    #clientId = ""           # Your client ID
    #clientSecret = ""       # Your client secret

  #[utterances]       # https://utteranc.es/
    #owner = ""              # Your GitHub ID
    #repo = ""               # The repo to store comments

  #[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
    #owner = ""              # Your GitHub ID
    #repo = ""               # The repo to store comments
    #clientId = ""           # Your client ID
    #clientSecret = ""       # Your client secret

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [valine]
    enable = false
    #appId = '你的appId'
    #appKey = '你的appKey'
    #notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    #verify = false # Verification code
    #avatar = 'mm'
    #placeholder = '说点什么吧...'
    #visitor = false

  #[changyan]
    #changyanAppid = ""        # Changyan app id             # 畅言
    #changyanAppkey = ""       # Changyan app key

  #[livere]
    #livereUID = ""            # LiveRe UID                  # 来必力

  # Isso: https://posativ.org/isso/
  #[isso]
    #enable = false
    #scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
    #dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

  # We are not using this
  #[socialOptions]
    #email = "mailto:your@email.com"
    #phone = ""
    #facebook = "http://example.org/"
    #twitter = "http://example.org/"
    #github = "https://github.com/zzossig/hugo-theme-zzo"
    #stack-overflow = ""
    #instagram = ""
    #google-plus = ""
    #youtube = ""
    #medium = ""
    #tumblr = ""
    #linkedin = ""
    #pinterest = ""
    #stack-exchange = ""
    #telegram = ""
    #steam = ""
    #weibo = ""
    #douban = ""
    #csdn = ""
    #gitlab = ""
    #mastodon = ""
    #jianshu = ""
    #zhihu = ""
    #signal = ""
    #whatsapp = ""
    #matrix = ""
    #xmpp = ""
    #dev-to = ""
    #gitea = ""
    #google-scholar = ""

  # We are not using this
  [donationOptions]
    enable = false
    #alipay = ""
    #wechat = ""
    #paypal = ""
    #patreon = ""

  # possible share name: ["facebook", "twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "telegram", "whatsapp", "pocket", "feedly", "hatena", "pinterest"]
  [[share]]
    name = "facebook"
    username = "YourOnly.ONE.ofcl"
  [[share]]
    name = "line"
  [[share]]
    name = "linkedin"
  [[share]]
    name = "pinterest"
  [[share]]
    name = "reddit"
  [[share]]
    name = "tumblr"
  [[share]]
    name = "twitter"

  # We are not using this, we edited the footer template directly
  #[[footerLinks]]
    #name = ""
    #link = ""
  #[[footerLinks]]
    #name = ""
    #link = ""
### END: Theme settings

### BGN: Hugo module settings ###
  ##### BGN: syndication #####
    ## Custom entries only work if placed in per-site params.toml ##
    [[sns]]
      url = 'is.youronly.one'
      icon = 'bluesky.svg'
    [[sns]]
      url = 't.youronly.one'
      icon = 'tumblr.svg'

    ## Defaults
    [[sns]]
      url = 'blogspot.com'
      icon = 'blogspot.svg'
    [[sns]]
      url = 'bsky.app'
      icon = 'bluesky.svg'
    [[sns]]
      url = 'c.im'
      icon = 'mastodon.png'
    [[sns]]
      url = 'c.wtf'
      icon = 'rebased.svg'
    [[sns]]
      url = 'catodon.social'
      icon = 'catodon.png'
    [[sns]]
      url = 'coracle.social'
      icon = 'nostr.svg'
    [[sns]]
      url = 'diasp.org'
      icon = 'diaspora.svg'
    [[sns]]
      url = 'ebin.club'
      icon = 'fediverse.svg'
    [[sns]]
      url = 'facebook.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fb.com'
      icon = 'facebook.svg'
    [[sns]]
      url = 'fedia.io'
      icon = 'mbin.svg'
    [[sns]]
      url = 'fedia.social'
      icon = 'iceshrimp.png'
    [[sns]]
      url = 'instagram.com'
      icon = 'instagram.svg'
    [[sns]]
      url = 'iris.to'
      icon = 'nostr.svg'
    [[sns]]
      url = 'mastodon.online'
      icon = 'mastodon.png'
    [[sns]]
      url = 'mastodon.social'
      icon = 'mastodon.png'
    [[sns]]
      url = 'naver.com'
      icon = 'naver.png'
    [[sns]]
      url = 'njump.me'
      icon = 'nostr.svg'
    [[sns]]
      url = 'nosta.me'
      icon = 'nostr.svg'
    [[sns]]
      url = 'p.lu'
      icon = 'peertube.svg'
    [[sns]]
      url = 'pixelfed.social'
      icon = 'pixelfed.svg'
    [[sns]]
      url = 'plurk.com'
      icon = 'plurk.svg'
    [[sns]]
      url = 'primal.net'
      icon = 'nostr.svg'
    [[sns]]
      url = 'reddit.com'
      icon = 'reddit.svg'
    [[sns]]
      url = 'satellite.earth'
      icon = 'nostr.svg'
    [[sns]]
      url = 'snort.social'
      icon = 'nostr.svg'
    [[sns]]
      url = 'socialhome.network'
      icon = 'socialhome-black.svg'
    [[sns]]
      url = 'spoutible.com'
      icon = 'spoutible.png'
    [[sns]]
      url = 'threads.net'
      icon = 'threads.svg'
    [[sns]]
      url = 'tumblr.com'
      icon = 'tumblr.svg'
    [[sns]]
      url = 'twitter.com'
      icon = 'twitter.svg'
    [[sns]]
      url = 'wordpress.com'
      icon = 'wordpress.svg'
    [[sns]]
      url = 'write.as'
      icon = 'writefreely.png'
    [[sns]]
      url = 'x.com'
      icon = 'x.svg'
    [[sns]]
      url = 'youtube.com'
      icon = 'youtube.svg'
  ##### END: syndication #####
### END: Hugo module settings ###

### BGN: Other Settings ###
  [semweb]
    datecreated = "2003-12-12"
    isblog = true
    sameas = [
      "https://www.facebook.com/techmagus",
      "https://c.im/@YourOnlyOne",
      "https://pixelfed.social/YourOnlyOne",
      "https://www.youtube.com/@YourOnlyOneOfcl",
      "https://www.facebook.com/YourOnly.ONE.ofcl"
    ]

  [tools]
    #onesignal = "79058a23-5e2c-4862-926f-37d20de118e5"
### END: Other Settings ###
