#mainSections = ["blog", "c"]

googleTagManager = "GTM-KT65GHZ"
subdir = "techmagus"
rssfull = "true"
faviconcache = "fmgy"
faviconbuster = "TimmieIsMyFate"
jquerycdn = true

### BGN: Structured Data ###
  siteStartYear = 2021

  description = "Science and Technology Playgground."
  license = "https://im.youronly.one/p/legal-notice/"
  #issn = ""
  #awards = [""]
  images = ["https://rsc.youronly.one/img/y/YOOki_Chronicles.webp"]

  name = "YourOnly.One" # your company name
  primaryauthor = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)" # Used as primary author if no specific is set
  ownerhomepage = "https://youronly.one"
  alternatenames = [ "JC John Sese Cuneta", "Yuki"]
  gender = "https://schema.org/Male"
  knowslanguages = ["en-PH", "fil", "tl-Tglg"]
  nationality = "Filipino"

  copyright = ""
  copyrightnotice = "JC John Sese Cuneta"
  copyrightyear = "2021"      # same as datePublished

  logourl = "https://rsc.youronly.one/img/y/techmagus-Architetto-Esperiment-chimico.webp" # Used in structured data as logo url
  keywords = ["YourOnly.One", "Yuki", "ᜌᜓᜃᜒ", "techmagus"] # Can be overriden per page
  imageurl = "https://rsc.youronly.one/img/y/techmagus-Architetto-Esperiment-chimico.webp" # Used in structured data as background image

  #contact = "" # Primary email address
  #phone = "" # Primary phone
  #primarylocation = "" # Used as primary location if no specific is set

  color = "#000000"
  pricerange = "" # Used in structured data as price range
### END: Structured Data ###

### BGN: Theme settings
  #logoText = "techmagus"                                                     # We are not using this
  logoType = "short" # long, short
  #custom_css = []
  #custom_js = []
  useFaviconGenerator = false # https://www.favicon-generator.org/
  meta_image = ""
  themecolor = ""

  themeOptions = ["kimbie", "solarized", "hacker", "light", "dark"]
  notAllowedTypesInHome = ["contact", "talks", "about", "showcase", "publication", "presentation", "resume"]
  notAllowedTypesInHomeSidebar = ["about", "archive", "showcase", "publication", "presentation", "resume"]
  notAllowedTypesInArchive = ["about", "talks", "showcase", "publication", "presentation", "resume"]
  notAllowedTypesInHomeFeed = ["about", "archive", "contact", "talks", "showcase", "publication", "presentation", "resume", "gallery"]

  viewportSize = "wide" # widest, wider, wide, normal, narrow
  enableUiAnimation = true
  hideSingleContentsWhenJSDisabled = false
  enablePinnedPosts = true
  minItemsToShowInTagCloud = 1 # Minimum items to show in tag cloud

  # appbar
  enableAppbarSearchIcon = true
  enableAppbarLangIcon = true

  # header
  homeHeaderType = "text" # text, img, slide, typewriter
  hideHomeHeaderWhenMobile = false

  # menu
  showMobileMenuTerms = ["series", "categories", "tags"]

  # search
  enableSearch = true
  enableSearchHighlight = true
  searchResultPosition = "side" # side, main
  searchContent = true # include content to search index
  searchDistance = 100 # fuse option
  searchThreshold = 0.4 # 0.0: exact match, 1.0: any match

  # body
  enableBreadcrumb = false
  enableGoToTop = true
  enableWhoami = false
  summaryShape = "classic" # card, classic, compact
  archiveGroupByDate = "2006-01" # "2006-01": group by month, "2006": group by year
  archivePaginate = 10
  paginateWindow = 1
  talksPaginate = 5
  talksGroupByDate = "2006-01"
  pubPaginate = 20
  writtenTimeIcon = "📅"
  modifiedTimeIcon = "📝"
  readingTimeIcon = "☕"
  #authorIcon = "✍️"                                                            # We are not using this.
  pagePvIcon = "👀"
  pinIcon = "📌"
  tagIcon = "🏷️"
  publicationIcon = "📚"
  typeIcon = "🎯"

  # We are not using this
  # whoami
  #myname = ""
  #email = ""
  #whoami = ""
  #bioImageUrl = ""
  #useGravatar = false
  #location = ""
  #organization = ""
  #link = ""

  # sidebar
  enableBio = false
  enableBioImage = true
  enableSidebar = true
  enableSidebarTags = true
  enableSidebarSeries = true
  enableSidebarCategories = true
  enableSidebarChannels = false
  enableHomeSidebarTitles = true
  enableListSidebarTitles = true
  enableToc = true
  hideToc = false
  tocFolding = true
  tocPosition = "inner" # inner, outer
  enableTocSwitch = true
  itemsPerCategory = 5
  sidebarPosition = "right"
  tocLevels = ["h2", "h3", "h4"]
  enableSidebarPostsByOrder = false

  # footer
  showPoweredBy = true
  showFeedLinks = true
  showSocialLinks = true
  enableLangChange = true
  enableThemeChange = true

  # service
  #googleTagManager = ""                                          # We already have this set on our own (see top of this file)
  #baiduAnalytics = ""
  enableBusuanzi = false
  busuanziSiteUV = true
  busuanziSitePV = true
  busuanziPagePV = true

  # rss
  updatePeriod = "" # Possible values: 'hourly', 'daily', 'weekly', 'monthly', or 'yearly'.
  updateFrequency = ""
  fullContents = true

  # comment
  enableComment = true
  #disqus_shortname = ""                                          # We are using the default disqus param
  commento = false

  [telegram]
    enable = false
    #siteId = ""
    #dataLimit = 5

  #[gitment]          # Gitment is a comment system based on GitHub issues. see https://github.com/imsun/gitment
    #owner = ""              # Your GitHub ID
    #repo = ""               # The repo to store comments
    #clientId = ""           # Your client ID
    #clientSecret = ""       # Your client secret

  #[utterances]       # https://utteranc.es/
    #owner = ""              # Your GitHub ID
    #repo = ""               # The repo to store comments

  #[gitalk]           # Gitalk is a comment system based on GitHub issues. see https://github.com/gitalk/gitalk
    #owner = ""              # Your GitHub ID
    #repo = ""               # The repo to store comments
    #clientId = ""           # Your client ID
    #clientSecret = ""       # Your client secret

  # Valine.
  # You can get your appid and appkey from https://leancloud.cn
  # more info please open https://valine.js.org
  [valine]
    enable = false
    #appId = '你的appId'
    #appKey = '你的appKey'
    #notify = false  # mail notifier , https://github.com/xCss/Valine/wiki
    #verify = false # Verification code
    #avatar = 'mm' 
    #placeholder = '说点什么吧...'
    #visitor = false

  #[changyan]
    #changyanAppid = ""        # Changyan app id             # 畅言
    #changyanAppkey = ""       # Changyan app key

  #[livere]
    #livereUID = ""            # LiveRe UID                  # 来必力

  # Isso: https://posativ.org/isso/
  #[isso]
    enable = false
    #scriptSrc = "" # "https://isso.example.com/js/embed.min.js"
    #dataAttrs = "" # "data-isso='https://isso.example.com' data-isso-require-author='true'"

  # We are not using this
  #[socialOptions]
    #email = "mailto:your@email.com"
    #phone = ""
    #facebook = "http://example.org/"
    #twitter = "http://example.org/"
    #github = "https://github.com/zzossig/hugo-theme-zzo"
    #stack-overflow = ""
    #instagram = ""
    #google-plus = ""
    #youtube = ""
    #medium = ""
    #tumblr = ""
    #linkedin = ""
    #pinterest = ""
    #stack-exchange = ""
    #telegram = ""
    #steam = ""
    #weibo = ""
    #douban = ""
    #csdn = ""
    #gitlab = ""
    #mastodon = ""
    #jianshu = ""
    #zhihu = ""
    #signal = ""
    #whatsapp = ""
    #matrix = ""
    #xmpp = ""
    #dev-to = ""
    #gitea = ""
    #google-scholar = ""

  [donationOptions]
    enable = false
    #alipay = ""
    #wechat = ""
    paypal = "https://paypal.me/yukino/"
    #patreon = ""

  # possible share name: ["facebook", "twitter", "reddit", "linkedin", "tumblr", "weibo", "douban", "line", "telegram", "whatsapp", "pocket", "feedly", "hatena", "pinterest"]
  [[share]]
    name = "facebook"
    username = "YourOnly.One0"
  [[share]]
    name = "hatena"
  [[share]]
    name = "line"
  [[share]]
    name = "linkedin"
  [[share]]
    name = "pinterest"
  [[share]]
    name = "reddit"
  [[share]]
    name = "telegram"
  [[share]]
    name = "tumblr"
  [[share]]
    name = "twitter"
  [[share]]
    name = "whatsapp"

  # We are not using this, we edited the footer template directly
  #[[footerLinks]]
    #name = ""
    #link = ""
  #[[footerLinks]]
    #name = ""
    #link = ""
### END: Theme settings

### BGN: Other Settings ###
  [author]                                                    # .Param "author.key"
    name = "ᜌᜓᜃᜒ (Yuki ・ 雪亮)"
    email = ""
    homepage = "https://youronly.one"
    avatar = "https://rsc.youronly.one/img/y/Yuki_flag-square-300x.webp"
    #emoji = "&#x1FAF0;&#x1F3FE;"
    emoji = "❄️"
    descriptionshort = "Born a writer and programmer."
    descriptionlong = "Lives in the Philippines and have been writing and programming at a young age."
    motto = "If this is not the end of oblivion, then I shall live everyday as if my life were to end on this very day."
    locationorigin = "Philippines"
    locationcurrent = "Philippines"
    organization = "Yelosan Publishing"

    rel = "me noopener"
    #rel = "noopener external nofollow"

  [siteowner]
    given_name = "Yahuhanan Yukia"
    middle_name = "Sese"
    family_name = "Cuneta"

  [semweb.publisher]
    name = "YourOnly.One"
    sameas = "https://youronly.one"

  [verify]
    naver = "0212955cb24d6e2c67f92be3c7833cae8a98fa8e"
    wot = "06c7ef6e7986586661ef"
### END: Other Settings ###
